"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {MapEvent} from "../lib/events";
import {africaFeatures} from "../lib/geo";
import {X,Plus,Minus,MapPin,ExternalLink,RefreshCw} from "lucide-react";

const categories=["All","Business","Infrastructure","Tech","Event","Weather","Aviation"] as const;
const ranges=["LIVE","24H","7D","30D"] as const;
const maxAge=(range:string)=>range==="LIVE"?0:range==="24H"?1:range==="7D"?7:30;
const confidenceOf=(event:MapEvent)=>{const value=(event as MapEvent & {confidence?:string}).confidence;return value==="high"||value==="medium"||value==="low"?value:"unknown"};
const project=(lat:number,lng:number)=>({x:5+((lng+25)*90/80),y:5+((37-lat)*90/73)});

export default function Home(){
 const [range,setRange]=useState<typeof ranges[number]>("LIVE");
 const [category,setCategory]=useState("All");
 const [selected,setSelected]=useState<MapEvent|null>(null);
 const [country,setCountry]=useState<string|null>(null);
 const [zoom,setZoom]=useState(1); const [pan,setPan]=useState({x:0,y:0}); const [drag,setDrag]=useState<{x:number;y:number;px:number;py:number;moved:boolean}|null>(null); const wasDraggingRef=useRef(false); const [weather,setWeather]=useState<MapEvent[]>([]); const [gdelt,setGdelt]=useState<MapEvent[]>([]); const [aviation,setAviation]=useState<MapEvent[]>([]); const aviationTrackRef=useRef<Record<string,{lat:number;lng:number}[]>>({}); const [aviationTracks,setAviationTracks]=useState<Record<string,{lat:number;lng:number}[]>>({}); const [weatherLoading,setWeatherLoading]=useState(true); const [gdeltLoading,setGdeltLoading]=useState(true); const [aviationLoading,setAviationLoading]=useState(true);
 const loadWeather=async()=>{setWeatherLoading(true);try{const r=await fetch("/api/weather");const j=await r.json();setWeather(j.signals??[]);}finally{setWeatherLoading(false);}};
 const loadGdelt=async()=>{setGdeltLoading(true);try{const r=await fetch("/api/gdelt");const j=await r.json();setGdelt(j.signals??[]);}finally{setGdeltLoading(false);}};
 const loadAviation=async()=>{setAviationLoading(true);try{const r=await fetch("/api/aviation");const j=await r.json();const next=(j.signals??[]) as MapEvent[];const previous=aviationTrackRef.current;const tracks={...previous};next.forEach(e=>{const history=tracks[e.id]??[];const last=history[history.length-1];if(!last||last.lat!==e.lat||last.lng!==e.lng)tracks[e.id]=[...history,{lat:e.lat,lng:e.lng}].slice(-8);});const activeIds=new Set(next.map(e=>e.id));Object.keys(tracks).forEach(id=>{if(!activeIds.has(id))delete tracks[id]});aviationTrackRef.current=tracks;setAviationTracks({...tracks});setAviation(next);}finally{setAviationLoading(false);}};
 useEffect(()=>{const id=window.setInterval(loadAviation,300000);return()=>window.clearInterval(id);},[]);
 useEffect(()=>{loadWeather();loadGdelt();loadAviation();},[]);
 const allEvents=useMemo(()=>[...weather,...gdelt,...aviation],[weather,gdelt,aviation]);
 const countryCounts=useMemo(()=>Object.fromEntries(africaFeatures.map(f=>[f.name,allEvents.filter(e=>e.country===f.name).length])),[allEvents]);
 const countryBreakdown=useMemo(()=>{if(!country)return [];const counts=new Map<string,number>();allEvents.filter(e=>e.country===country).forEach(e=>counts.set(e.category,(counts.get(e.category)??0)+1));return [...counts.entries()].sort((a,b)=>b[1]-a[1]);},[allEvents,country]);
 const visible=useMemo(()=>{const age=maxAge(range);return allEvents.filter(e=>(category==="All"||e.category===category)&&e.ageDays<=age&&(!country||e.country===country));},[allEvents,category,range,country]);
 return <main className="app">
  <header className="topbar"><div><span className="brand">Afrilayer</span><span className="tagline">See what&apos;s happening across Africa.</span><span className="live-badge" style={{marginLeft:8}}>LIVE DATA</span></div><div className="controls">{ranges.map(r=><button key={r} className={`control ${range===r?"active":""}`} onClick={()=>setRange(r)}>{r}</button>)}<button className="control" onClick={()=>{loadWeather();loadGdelt();loadAviation()}} title="Refresh live sources"><RefreshCw size={14}/></button></div></header>
  <section className="workspace"><div className="mapwrap">
   <div className="maptitle"><strong>{country||"Africa"}</strong><small>{visible.length} activity signals</small>{country&&<button className="clearcountry" onClick={()=>setCountry(null)}>Clear country</button>}</div>
   {country&&<div className="countrybreakdown"><div className="eyebrow">Signal breakdown</div>{countryBreakdown.length?<div className="breakdownrow">{countryBreakdown.map(([name,count])=><span key={name} className="breakdownitem"><b>{count}</b> {name}</span>)}</div>:<small>No signals mapped to this country yet.</small>}</div>}
   {selected&&visible.some(e=>e.id===selected.id)&&<div className="selectedpanel"><button className="close" onClick={()=>setSelected(null)}><X size={16}/></button><div className="eyebrow">{selected.category} · {selected.time}</div><h3>{selected.title}</h3><p>{selected.summary}</p><div className="location"><MapPin size={12} style={{verticalAlign:"-2px"}}/> {selected.city}, {selected.country}</div><div className="source">Source: {selected.source} · Confidence: {confidenceOf(selected)}{selected.sourceUrl&&<a href={selected.sourceUrl} target="_blank" rel="noreferrer">Open source <ExternalLink size={11}/></a>}</div></div>}
   <svg className="map" viewBox="0 0 100 100" preserveAspectRatio="none" style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`,transformOrigin:"50% 50%",cursor:drag?"grabbing":"grab",touchAction:"none"}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);wasDraggingRef.current=false;setDrag({x:pan.x,y:pan.y,px:e.clientX,py:e.clientY,moved:false})}} onPointerMove={e=>{if(!drag)return;const dx=e.clientX-drag.px,dy=e.clientY-drag.py;const moved=drag.moved||Math.abs(dx)+Math.abs(dy)>4;if(moved)wasDraggingRef.current=true;setDrag({...drag,moved});setPan({x:drag.x+dx,y:drag.y+dy})}} onPointerUp={()=>setDrag(null)} onPointerCancel={()=>setDrag(null)}>
    <defs><pattern id="grid" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M5 0H0V5" fill="none" stroke="#758089" strokeWidth=".08"/></pattern></defs><rect width="100" height="100" fill="url(#grid)" className="mapgrid"/>
    {africaFeatures.map(f=>{const count=countryCounts[f.name]??0;const density=Math.min(count/8,1);return <g key={f.id}><path d={f.path} className={`country ${country===f.name?"selectedcountry":""}`} style={{fillOpacity:country===f.name?1:.42+density*.38}} title={`${f.name}${count?` · ${count} signals`:""}`} onClick={()=>{setCountry(f.name);setSelected(null)}}/>{count>0&&<text className="countrycount" x={f.labelX} y={f.labelY}>{count}</text>}</g>})}
    <path d="M30 26L39 23 48 25 57 22 67 25 73 31M28 39L39 38 50 40 61 37 73 41M30 52L41 50 52 53 65 49 71 54M35 64L46 62 57 65 67 60M40 76L50 73 60 76" fill="none" stroke="#3b474e" strokeWidth=".18" opacity=".8"/>
    {visible.map(e=>{const p=project(e.lat,e.lng);const track=aviationTracks[e.id]??[];return <g key={e.id} onClick={()=>{if(!wasDraggingRef.current)setSelected(e)}}>{e.category==="Aviation"&&track.length>1&&<polyline className="flighttrail" points={track.map(point=>{const q=project(point.lat,point.lng);return `${q.x},${q.y}`}).join(" ")}/>}<circle className={`marker ${e.category==="Aviation"?"aircraft":e.hot?"hot":e.category==="Event"?"event":e.category==="Tech"?"tech":""}`} cx={p.x} cy={p.y} r={e.category==="Aviation"?1.05:e.hot?1.25:.85}/>{e.category==="Aviation"&&<path className="plane" d={`M ${p.x} ${p.y-1.8} L ${p.x+.65} ${p.y+.9} L ${p.x} ${p.y+.35} L ${p.x-.65} ${p.y+.9} Z`} transform={`rotate(${e.heading??0} ${p.x} ${p.y})`}/>}{e.hot&&<circle cx={p.x} cy={p.y} r="2.3" fill="none" stroke="#ffbd5c" strokeWidth=".18" opacity=".7"/>}</g>})}
   </svg><div className="zoom"><button onClick={()=>setZoom(z=>Math.min(1.5,z+.1))}><Plus size={15}/></button><button onClick={()=>setZoom(z=>Math.max(.8,z-.1))}><Minus size={15}/></button></div><div className="legend"><span><i style={{background:"#d9ff52"}}/>Activity</span><span><i style={{background:"#ffbd5c"}}/>Hot</span><span><i style={{background:"#c59cff"}}/>Tech</span><span><i style={{background:"#67d7ff"}}/>Weather</span></div><div className="footerline">{weatherLoading?"Updating live weather…":weather.length?`Live weather · ${weather.length} locations · GDELT ${gdeltLoading?"updating":`${gdelt.length}`} · Aircraft ${aviationLoading?"updating":aviation.length}`:"Live weather unavailable"} · All production signals come from live sources</div>
  </div><aside className="side"><div className="sidehead"><div className="eyebrow">{range==="LIVE"?"Live view":range}{country&&` · ${country}`}</div><h1>What&apos;s happening?</h1><p>Explore activity across Africa by place, category and time.</p></div><div className="filters">{categories.map(c=><button key={c} className={`control ${category===c?"active":""}`} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="feed">{visible.map(e=><article key={e.id} className={`card ${selected?.id===e.id?"selected":""}`} onClick={()=>setSelected(e)}><div className="meta"><span><i className="dot"/> {e.category}</span><span>{e.time}</span></div><h2>{e.title}</h2><p>{e.summary}</p><div className="location">{e.city}, {e.country}</div><div className="signal-source"><span className={e.source==="Demo signal"?"demo-badge":"live-badge"}>{e.source==="Demo signal"?"DEMO":"LIVE"}</span><span>{e.source}</span><span className={`confidence confidence-${confidenceOf(e)}`}>{confidenceOf(e)}</span></div></article>)}{visible.length===0&&<div className="empty">No activity in this layer yet.</div>}</div></aside></section>
 </main>;
}
